
ktor:
    application:
        modules:
            - "com.jacobrayschwartz.coffeetime.ApplicationKt.module"
    deployment:
        port: 8080
security:
    sessionEncryptKey: $SESSION_ENCRYPT_KEY
    sessionSignKey: $SESSION_SIGN_KEY
    okta:
        orgUrl: $OKTA_OAUTH2_ISSUER
        clientId: $OKTA_OAUTH2_CLIENT_ID
        clientSecret: $OKTA_OAUTH2_CLIENT_SECRET
db:
    postgres:
        host: localhost
        port: 5432
        database: coffee_time
        user: coffee_time
        password: coffee_time